import {test} from 'node:test';
import assert from 'node:assert/strict';
import {renderMarkdown,readingLink,pageHtml} from './build-docs.mjs';
test('renders headings, emphasis, nested lists and tables as readable HTML',()=>{const doc=renderMarkdown('# A **product** decision\n\nA *clear* choice.\n\n- First\n  - Nested\n\n| Choice | Cost |\n|---|---|\n| Scope | 2 days |','docs/product/Case_Study.md','Relevance-Studio');assert.equal(doc.title,'A product decision');for(const content of ['<strong>product</strong>','<em>clear</em>','<ul>','<table>','Scrollable table','2 days'])assert.ok(doc.html.includes(content));});
test('keeps GitHub heading anchors and makes repeated headings unique',()=>{const doc=renderMarkdown('# Case\n\n## Evidence & limits\n\n## Evidence & limits\n\n### 中文','docs/product/Case_Study.md','Relevance-Studio');assert.deepEqual(doc.headings.map(h=>h.id),['case','evidence--limits','evidence--limits-1','中文']);});
test('rewrites document paths and anchors while preserving external evidence',()=>{assert.equal(readingLink('Sample_Walkthrough.md#recovery','docs/product/Case_Study.md','Relevance-Studio'),'/Relevance-Studio/docs/product/Sample_Walkthrough.html#recovery');assert.equal(readingLink('../Product_Brief.md','docs/product/PRD.md','First-Mile'),'/First-Mile/docs/Product_Brief.html');assert.equal(readingLink('../../README.md','docs/product/PRD.md','Relevance-Studio'),'https://github.com/mvahedi2020/Relevance-Studio/blob/main/README.md');assert.equal(readingLink('https://example.com/source','docs/product/PRD.md','Relevance-Studio'),'https://example.com/source');assert.equal(readingLink('Sample%20Walkthrough.md','docs/product/PRD.md','Launch-Control'),'/Launch-Control/docs/product/Sample%20Walkthrough.html');});
test('does not execute authored HTML or unsafe links',()=>{const doc=renderMarkdown('# Safety\n\n<script>alert(1)</script>\n\n[bad](javascript:alert(1))\n\n![x](x" onerror="alert(1))','docs/product/PRD.md','Relevance-Studio');assert.ok(!doc.html.includes('<script>'));assert.ok(!doc.html.includes('href="javascript:'));assert.ok(!doc.html.includes(' onerror="'));});
test('reader includes a meaningful title, semantic navigation and local-only assets',()=>{const html=pageHtml({repo:'Relevance-Studio',title:'Relevance Studio',rel:'docs/product/Case_Study.md',rendered:renderMarkdown('# Decision\n\n## Tradeoff\n\nClear evidence.','docs/product/Case_Study.md','Relevance-Studio'),documents:[]});for(const part of ['<title>Decision · Relevance Studio</title>','Back to demo','Skip to document','aria-label="On this page"','href="#tradeoff"','name="color-scheme" content="light"','/Relevance-Studio/docs/reader.css',"object-src 'none'"])assert.ok(html.includes(part),part);});

test('appended document sections keep their anchors beneath one page title',()=>{const doc=renderMarkdown('# Main title\n\n## Original section\n\n# Later evidence\n\n## Its details','docs/product/Validation.md','Relevance-Studio');assert.deepEqual(doc.headings.map(h=>[h.level,h.id]),[[1,'main-title'],[2,'original-section'],[2,'later-evidence'],[3,'its-details']]);assert.equal((doc.html.match(/<h1 /g)??[]).length,1);});

test('aligned tables preserve meaning without CSP-blocked inline styles',()=>{const doc=renderMarkdown('# Measures\n\n| Left | Center | Right |\n|:---|:---:|---:|\n| A | B | 12 |','docs/product/PRD.md','Relevance-Studio');for(const alignment of ['left','center','right'])assert.ok(doc.html.includes(`class="align-${alignment}"`));assert.ok(!doc.html.includes('style='));});
