import { expect, test } from 'vitest'
import { commitDecision, loadSession, previewDecision, storageKey, type StoragePort } from './storage'
import { initialState, transition, type Context } from './domain'
const context: Context = { asset: 'poster', version: 'v1', role: 'reviewer' }
const action = { type: 'annotate' as const, anchor: 'details' as const, text: 'Make the date legible.' }
function port(raw: string | null = null) { return { raw, writes: 0, getItem(key: string) { expect(key).toBe(storageKey); return this.raw }, setItem(key: string, value: string) { expect(key).toBe(storageKey); this.raw = value; this.writes++ } } }
const fail = () => { throw new Error('Storage disabled') }
test('confirmed writes restore on refresh; previews are side effect free', () => { const p = port(); const s = loadSession(() => p); const preview = previewDecision(s, context, action); expect(p.writes).toBe(0); const result = commitDecision(s, preview.pending, context, () => p); expect(result.applied).toBe(true); expect(loadSession(() => p).state.revision).toBe(1) })
test('invalid data is preserved and blocks edits until explicit confirmed reset', () => { const p = port('{broken'); const s = loadSession(() => p); expect(s.mode).toBe('invalid'); expect(() => previewDecision(s, context, action)).toThrow('invalid'); const preview = previewDecision(s, context, { type: 'reset' }); expect(p.raw).toBe('{broken'); const result = commitDecision(s, preview.pending, context, () => p); expect(result.applied).toBe(true); expect(p.raw).toBe(JSON.stringify(initialState())) })
test('getter failure at hydration is explained', () => { expect(loadSession(fail)).toMatchObject({ mode: 'memory', state: initialState() }) })
test('getItem failure retains confirmed memory and permits explicit in-memory decisions', () => { const p = port(); let s = loadSession(() => p); s = commitDecision(s, previewDecision(s, context, action).pending, context, () => p).session; const broken: StoragePort = { getItem: fail, setItem: fail }; const loaded = loadSession(() => broken, s); expect(loaded.state).toEqual(s.state); const result = commitDecision(loaded, previewDecision(loaded, context, action).pending, context, () => broken); expect(result.applied).toBe(true); expect(result.session.state.revision).toBe(2); expect(result.session.mode).toBe('memory') })
test('setItem failure retains confirmed action in memory without overwriting stored bytes', () => { const p = port(); const s = loadSession(() => p); const result = commitDecision(s, previewDecision(s, context, action).pending, context, () => ({ getItem: p.getItem.bind(p), setItem: fail })); expect(result.applied).toBe(true); expect(result.session.state.revision).toBe(1); expect(result.session.mode).toBe('memory'); expect(p.raw).toBeNull() })
test('unavailable reset cannot destroy preserved invalid data', () => { const p = port('wrong'); const s = loadSession(() => p); const result = commitDecision(s, previewDecision(s, context, { type: 'reset' }).pending, context, fail); expect(result.applied).toBe(false); expect(p.raw).toBe('wrong') })
test('failed reset write preserves invalid bytes and current memory', () => { const p = port('wrong'); const s = loadSession(() => p); const result = commitDecision(s, previewDecision(s, context, { type: 'reset' }).pending, context, () => ({ getItem: p.getItem.bind(p), setItem: fail })); expect(result.applied).toBe(false); expect(result.session.state).toEqual(s.state); expect(p.raw).toBe('wrong') })
test('version or role change rejects pending preview', () => { const p = port(); const s = loadSession(() => p); const pending = previewDecision(s, context, action).pending; expect(commitDecision(s, pending, { ...context, role: 'approver' }, () => p).applied).toBe(false); expect(commitDecision(s, pending, { ...context, version: 'v2' }, () => p).applied).toBe(false); expect(p.writes).toBe(0) })
test('same-revision cross-tab divergence rejects stale action using full bytes', () => { const original = transition(initialState(), context, action); const p = port(JSON.stringify(original)); const s = loadSession(() => p); const pending = previewDecision(s, context, action).pending; const changed = structuredClone(original); changed.assets[0].versions[0].issues[0].text = 'Different issue on the same revision.'; p.raw = JSON.stringify(changed); const result = commitDecision(s, pending, context, () => p); expect(result.applied).toBe(false); expect(result.session.state).toEqual(changed); expect(p.writes).toBe(0) })
test('invalid cross-tab divergence is preserved and cancels pending commit', () => { const p = port(); const s = loadSession(() => p); const pending = previewDecision(s, context, action).pending; p.raw = 'invalid'; const result = commitDecision(s, pending, context, () => p); expect(result.applied).toBe(false); expect(result.session.mode).toBe('invalid'); expect(p.raw).toBe('invalid') })
test('state change within tab rejects previous pending action', () => { const p = port(); const s = loadSession(() => p); const pending = previewDecision(s, context, action).pending; const confirmed = commitDecision(s, pending, context, () => p).session; expect(commitDecision(confirmed, pending, context, () => p).applied).toBe(false) })
